//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReportFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentoes
    {
        public DateTime CreationDate { get; set; }
        public string Text { get; set; }
        public string Author_CodFisc { get; set; }
        public Nullable<System.DateTime> Segnalazione_CreationDate { get; set; }
    
        public virtual Segnalaziones Segnalaziones { get; set; }
        public virtual Utentes Utentes { get; set; }
    }
}
