//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReportFactory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BugReportDataBaseEntities : DbContext
    {
        public BugReportDataBaseEntities()
            : base("name=BugReportDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Commentoes> Commentoes { get; set; }
        public virtual DbSet<Prodottoes> Prodottoes { get; set; }
        public virtual DbSet<Segnalaziones> Segnalaziones { get; set; }
        public virtual DbSet<Utentes> Utentes { get; set; }
    }
}
