//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReportFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segnalaziones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segnalaziones()
        {
            this.Commentoes = new HashSet<Commentoes>();
        }
    
        public System.DateTime CreationDate { get; set; }
        public string State { get; set; }
        public string Descr { get; set; }
        public string Text { get; set; }
        public string Author_CodFisc { get; set; }
        public Nullable<int> SigProd_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentoes> Commentoes { get; set; }
        public virtual Prodottoes Prodottoes { get; set; }
        public virtual Utentes Utentes { get; set; }
    }
}
