//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReportFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utentes()
        {
            this.Commentoes = new HashSet<Commentoes>();
            this.Segnalaziones = new HashSet<Segnalaziones>();
        }
    
        public string CodFisc { get; set; }
        public string LogIn { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Dob { get; set; }
        public int Age { get; set; }
        public string Indirizzo_Via { get; set; }
        public int Indirizzo_Civico { get; set; }
        public int Indirizzo_Interno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentoes> Commentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segnalaziones> Segnalaziones { get; set; }
    }
}
